name: Run Postman Collection

on:
  push:
    branches:
      - master

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Install Newman
      run: npm install -g newman newman-reporter-html

    - name: Run Newman with HTML report
      run: newman run ./petstore.collection.json -r cli,html --reporter-html-export newman-report.html
      continue-on-error: true

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git fetch
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        mv newman-report.html index.html
        git add index.html
        git commit -m "Update Newman report on GitHub Pages"
        git push -f https://${{ secrets.GH_PAGES_SECRET }}@github.com/${{ github.repository }}/ gh-pages
