name: Run Postman Collection and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # This triggers the workflow on pushes to the master branch.

jobs:
  run-newman:
    runs-on: ubuntu-latest  # Specifies that the job runs on the latest version of Ubuntu.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # Uses the actions/checkout@v3 action to check out the repository code.

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      # This step uses actions/setup-node to set up a Node.js environment with version 20.

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
      

    - name: Run Newman with HTML report
      run: newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export newman-report.html --reporter-htmlextra-darkTheme
      continue-on-error: true
      # Runs Newman to execute the Postman collection and generates an HTML report.
      # The continue-on-error: true setting ensures the workflow continues even if Newman tests fail.

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git fetch
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        mv newman-report.html index.html
        git add index.html
        git commit -m "Update Newman report on GitHub Pages"
        git push -f https://${{ secrets.GH_PAGES }}@github.com/kiteamismorethansport/postmanApiTests gh-pages
      #All done
      
      

